#!/bin/bash -l
#PBS -A NAML0001
#PBS -M dkimpara@ucar.edu
#PBS -q casper
#PBS -m a
#PBS -N rap_disagree_0
#PBS -l walltime=00:45:00
#PBS -l select=1:ncpus=24:mem=1000GB
#PBS -o outfiles/rap_disagree_0.out
#PBS -e outfiles/rap_disagree_0.out
export TMPDIR=/glade/scratch/$USER/temp
mkdir -p $TMPDIR
source /etc/profile.d/modules.sh
module load conda
conda activate ptype
cd /glade/u/home/dkimpara/ptype-physical/composite-soundings
mkdir -p outfiles
python -u /glade/u/home/dkimpara/ptype-physical/applications/map_reduce_run.py -i 0 -m rap -o rap_disagree_0 -f "xmr.compute_by_disagree"
