log: True
save_path: "/glade/work/schreck/repos/ptype-physical/results/echo"
pbs:
  jobs: 1
  bash: ["source ~/.bashrc", "conda activate ptype"]
  batch:
    l: ["select=1:ncpus=8:ngpus=1:mem=128GB", "walltime=12:00:00", "gpu_type=v100"]
    A: "NAML0001"
    q: "casper"
    N: "echo_trial"
    o: "/glade/work/schreck/repos/ptype-physical/results/echo/p-type.out"
    e: "/glade/work/schreck/repos/ptype-physical/results/echo/p-type.err"
optuna:
  study_name: "mlp_optimization"
  storage: "echo.db"
  storage_type: "sqlite"
  objective: "/glade/work/schreck/repos/ptype-physical/applications/train_classifier_keras.py"
  metric: "val_f1"
  direction: "maximize"
  n_trials: 1000
  gpu: True
  sampler:
    type: "TPESampler"
    n_startup_trials: 100 
  parameters:
    model:hidden_layers:
      type: "int"
      settings:
        name: "hidden_layers"
        low: 1
        high: 20
    model:hidden_neurons:
      type: "int"
      settings:
        name: "hidden_neurons"
        low: 50
        high: 1000
    model:dropout_alpha:
      type: "float"
      settings:
        name: "dropout_alpha"
        low: 0.0
        high: 0.5
    model:lr:
      type: "loguniform"
      settings:
        name: "lr"
        low: 0.0000001
        high: 0.01
    model:activation:
      type: "categorical"
      settings:
        name: "activation"
        choices: ["relu", "leaky", "elu", "selu"]
    model:batch_size:
      type: "int"
      settings:
        name: "batch_size"
        low: 1000
        high: 50000
    model:l2_weight:
      type: "loguniform"
      settings:
        name: "l2_weight"
        low: 0.0000000001
        high: 0.01
    rain_weight:
      type: "float"
      settings:
        name: "rain_weight"
        low: 0.001
        high: 100
    snow_weight:
      type: "float"
      settings:
        name: "snow_weight"
        low: 0.001
        high: 100
    sleet_weight:
      type: "float"
      settings:
        name: "sleet_weight"
        low: 0.001
        high: 1000
    frz_rain_weight:
      type: "float"
      settings:
        name: "frz_rain_weight"
        low: 0.001
        high: 1000