model: "hrrr"
evidential: True
ML_model_path: "/glade/p/cisl/aiml/ai2es/winter_ptypes/models/evidential_weighted"
input_scaler_file: "input.json"
out_path: "/glade/work/username/ptype_real_time/2023-11-17/"
drop_input_data: False
add_interp_data: True
n_processors: 20      # Only used if use_dask=False (dask has its own parameters at bottom of config)
use_dask: False
save_format: "netcdf"   # Supports "zarr" and "netcdf"
extent: [-115, -110, 32, 35]  # [min_lon, max_lon, min_lat, max_lat] or "full"
dates:
  most_recent: True
  start: "2022-02-03 00:00" # ignore if most_recent is True
  end: "2022-02-03 05:00"   # ignore if most_recent is True
  frequency: "1H"

forecast_range:
  start: 1
  end: 18
  interval: 1

height_levels:
  low: 0
  high: 5000
  interval: 250

variables:
  model:
    rap:
      isobaricInhPa: ["t", "u", "v", "r", "gh"]
      surface: ["orog", "crain", "csnow", "cicep", "cfrzr"]
      heightAboveGround: ["t2m", "d2m", "u10", "v10"]
      product: "awp130pgrb"
    hrrr:
      isobaricInhPa: ["t", "u", "v", "dpt", "gh"]
      surface: ["orog", "crain", "csnow", "cicep", "cfrzr"]
      heightAboveGround: ["t2m", "d2m", "u10", "v10"]
      product: "prs"
    gfs:
      isobaricInhPa: [ "t", "u", "v", "q", "gh" ]
      surface: ["orog", "crain", "csnow", "cicep", "cfrzr"]
      heightAboveGround: [ "t2m", "d2m", "u10", "v10" ]
      product: "pgrb2.0p25"
    nam:
      isobaricInhPa: [ "t", "u", "v", "dpt", "gh" ]
      surface: ["orog", "crain", "csnow", "cicep", "cfrzr"]
      heightAboveGround: [ "t2m", "d2m", "u10", "v10" ]
      product: "conusnest.hiresf"

dask_params:
  PBS:
    resource_spec: "select=1:ncpus=12:mem=128GB"
    processes: 12
    project: "NAML0001"
    n_workers: 1
    queue: "casper"
    walltime: "02:00:00"
    memory: "1TB"
    interface: "ib0"
    local_directory: "/glade/work/cbecker/ptype-physical/dask/"
    log_directory: "/glade/work/cbecker/ptype-physical/dask_logs/"
  n_jobs: 10
