model: "hrrr"
evidential: True
ML_model_path: "/glade/derecho/scratch/cbecker/evi_model_ptype_050124.keras"
input_scaler_file: "/glade/derecho/scratch/cbecker/evi_scaler.json"
out_path: "/glade/derecho/scratch/username/ptype_real_time/central_region/"
drop_input_data: False
add_interp_data: True
n_processors: 18      # Only used if use_dask=False (dask has its own parameters at bottom of config)
use_dask: False
save_format: "netcdf"   # Supports "zarr" and "netcdf"
extent: [-108, -89, 36, 48]  # [min_lon, max_lon, min_lat, max_lat] or "full"
dates:
  most_recent: True
  start: "2022-02-03 00:00" # ignore if most_recent is True
  end: "2022-02-03 05:00"   # ignore if most_recent is True
  frequency: "1H"

forecast_range:
  start: 1
  end: 18
  interval: 1

ml_atm_varaibles: ['t', 'dpt']

height_levels:
  low: 0
  high: 5000
  interval: 250

variables:
  model:
    rap:
      isobaricInhPa: ["t", "u", "v", "r", "gh"]
      surface: ["orog", "crain", "csnow", "cicep", "cfrzr"]
      heightAboveGround: ["t2m", "d2m", "u10", "v10"]
      kwargs:
        product: "awp130pgrb"
    hrrr:
      isobaricInhPa: ["t", "u", "v", "dpt", "gh"]
      surface: ["orog", "sp", "crain", "csnow", "cicep", "cfrzr", "tp"]
      atmosphere: ["refc"]
      heightAboveGround: ["t2m", "d2m", "u10", "v10"]
      kwargs:
        product: "prs"
    gfs:
      isobaricInhPa: [ "t", "u", "v", "q", "gh" ]
      surface: ["orog", "crain", "csnow", "cicep", "cfrzr"]
      heightAboveGround: [ "t2m", "d2m", "u10", "v10" ]
      kwargs:
        product: "pgrb2.0p25"
    nam:
      isobaricInhPa: [ "t", "u", "v", "dpt", "gh" ]
      surface: ["orog", "crain", "csnow", "cicep", "cfrzr"]
      heightAboveGround: [ "t2m", "d2m", "u10", "v10" ]
      kwargs:
        product: "conusnest.hiresf"
    gefs:
      isobaricInhPa: [ "t", "u", "v", "q", "gh" ]
      surface: [ "orog", "crain", "csnow", "cicep", "cfrzr" ]
      heightAboveGround: [ "t2m", "d2m", "u10", "v10" ]
      kwargs:
        product: "wave"
        member: "p11"

dask_params:
  PBS:
    resource_spec: "select=1:ncpus=12:mem=128GB"
    processes: 12
    project: "NAML0001"
    n_workers: 1
    queue: "casper"
    walltime: "02:00:00"
    memory: "1TB"
    interface: "ib0"
    local_directory: "/glade/work/cbecker/ptype-physical/dask/"
    log_directory: "/glade/work/cbecker/ptype-physical/dask_logs/"
  n_jobs: 10
